// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package senzingresttypedef

type SenzingRestAPITypedef = interface{}

type AddressData = []string

type CharacteristicData = []string

type Feature struct {
	DuplicateValues []string `json:"duplicateValues"`

	FeatureDetails []FeatureDetail `json:"featureDetails"`

	PrimaryID int64 `json:"primaryId"`

	PrimaryValue string `json:"primaryValue"`

	UsageType string `json:"usageType"`
}

type FeatureDetail struct {
	FeatureValue string `json:"featureValue"`

	InternalID int64 `json:"internalId"`
}

type FeatureScoreDetails struct {
	CandidateFeature string `json:"candidateFeature"`

	FeatureType string `json:"featureType"`

	InboundFeature string `json:"inboundFeature"`

	NameScoringDetails NameScoringDetails `json:"nameScoringDetails"`

	Score int64 `json:"score"`
}

type FeatureScores = interface{}

type Features struct {
	DefaultName Feature `json:"*"`
}

type IdentifierData = []string

type Links struct {
	OpenAPISpecification string `json:"openApiSpecification"`

	Self string `json:"self"`
}

type Meta struct {
	ConfigCompatibilityVersion string `json:"configCompatibilityVersion"`

	HTTPMethod string `json:"httpMethod"`

	HTTPStatusCode int32 `json:"httpStatusCode"`

	NativeAPIBuildDate string `json:"nativeApiBuildDate"`

	NativeAPIBuildNumber string `json:"nativeApiBuildNumber"`

	NativeAPIBuildVersion string `json:"nativeApiBuildVersion"`

	NativeAPIVersion string `json:"nativeApiVersion"`

	PocAPIVersion string `json:"pocApiVersion"`

	PocServerVersion string `json:"pocServerVersion"`

	RestAPIVersion string `json:"restApiVersion"`

	Server string `json:"server"`

	Timestamp string `json:"timestamp"`

	Timings Timings `json:"timings"`

	Version string `json:"version"`
}

type NameData = []string

type NameScoringDetails struct {
	HTTPSfullNameScore int32 `json:"httpSFullNameScore"`
}

type OtherData = []string

type PhoneData = []string

type Record struct {
	AddressData AddressData `json:"addressData"`

	CharacteristicData CharacteristicData `json:"characteristicData"`

	DataSource string `json:"dataSource"`

	IdentifierData IdentifierData `json:"identifierData"`

	LastSeenTimestamp string `json:"lastSeenTimestamp"`

	MatchKey string `json:"matchKey"`

	MatchLevel int32 `json:"matchLevel"`

	NameData NameData `json:"nameData"`

	OriginalSourceData interface{} `json:"originalSourceData"`

	OtherData OtherData `json:"otherData"`

	PhoneData PhoneData `json:"phoneData"`

	RecordID string `json:"recordId"`

	ResolutionRuleCode string `json:"resolutionRuleCode"`
}

type RecordSummeries = []RecordSummery

type RecordSummery struct {
	DataSource string `json:"dataSource"`

	RecordCount int64 `json:"recordCount"`

	TopRecordIds []string `json:"topRecordIds"`
}

type Records = []Record

type SearchEntitiesByGetResponse struct {
	Data SearchResultsData `json:"data"`

	Links Links `json:"links"`

	Meta Meta `json:"meta"`
}

type SearchResult struct {
	AddressData AddressData `json:"addressData"`

	BestNameScore int32 `json:"bestNameScore"`

	CharacteristicData CharacteristicData `json:"characteristicData"`

	EntityID string `json:"entityId"`

	EntityName string `json:"entityName"`

	FeatureScores FeatureScores `json:"featureScores"`

	Features Features `json:"features"`

	IdentifierData IdentifierData `json:"identifierData"`

	LastSeenTimestamp string `json:"lastSeenTimestamp"`

	MatchKey string `json:"matchKey"`

	MatchLevel int32 `json:"matchLevel"`

	NameData NameData `json:"nameData"`

	OtherData OtherData `json:"otherData"`

	Partial bool `json:"partial"`

	PhoneData PhoneData `json:"phoneData"`

	RecordSummeries RecordSummeries `json:"recordSummeries"`

	Records Records `json:"records"`

	ResolutionRuleCode string `json:"resolutionRuleCode"`

	ResultType string `json:"resultType"`
}

type SearchResults = []SearchResult

type SearchResultsData struct {
	SearchResults SearchResults `json:"searchResults"`
}

type Timings struct {
	Enqueued int64 `json:"enqueued"`

	NativeAPI int64 `json:"nativeAPI"`

	Overall int64 `json:"overall"`

	ProcessRawData int64 `json:"processRawData"`
}
