// Code generated by ogen, DO NOT EDIT.

package senzingrestapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"
			origElem := elem
			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch r.Method {
				case "GET":
					s.handleRootRequest([0]string{}, elemIsEscaped, w, r)
				default:
					s.notAllowed(w, r, "GET")
				}

				return
			}
			switch elem[0] {
			case 'a': // Prefix: "attribute-types"
				origElem := elem
				if l := len("attribute-types"); len(elem) >= l && elem[0:l] == "attribute-types" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetAttributeTypesRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "attributeCode"
					// Leaf parameter
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetAttributeTypeRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'b': // Prefix: "bulk-data/"
				origElem := elem
				if l := len("bulk-data/"); len(elem) >= l && elem[0:l] == "bulk-data/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "analyze"
					origElem := elem
					if l := len("analyze"); len(elem) >= l && elem[0:l] == "analyze" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleAnalyzeBulkRecordsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}

					elem = origElem
				case 'l': // Prefix: "load"
					origElem := elem
					if l := len("load"); len(elem) >= l && elem[0:l] == "load" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleLoadBulkRecordsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'c': // Prefix: "configs/"
				origElem := elem
				if l := len("configs/"); len(elem) >= l && elem[0:l] == "configs/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "active"
					origElem := elem
					if l := len("active"); len(elem) >= l && elem[0:l] == "active" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetActiveConfigRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				case 't': // Prefix: "template"
					origElem := elem
					if l := len("template"); len(elem) >= l && elem[0:l] == "template" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetTemplateConfigRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'd': // Prefix: "data-sources"
				origElem := elem
				if l := len("data-sources"); len(elem) >= l && elem[0:l] == "data-sources" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetDataSourcesRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleAddDataSourcesRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "dataSourceCode"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetDataSourceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/records"
						origElem := elem
						if l := len("/records"); len(elem) >= l && elem[0:l] == "/records" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "POST":
								s.handleAddRecordWithReturnedRecordIdRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "recordId"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleDeleteRecordRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetRecordRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAddRecordRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,GET,PUT")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'e': // Prefix: "entity"
									origElem := elem
									if l := len("entity"); len(elem) >= l && elem[0:l] == "entity" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch r.Method {
										case "GET":
											s.handleGetEntityByRecordIdRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "GET")
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/"
										origElem := elem
										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'h': // Prefix: "how"
											origElem := elem
											if l := len("how"); len(elem) >= l && elem[0:l] == "how" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "GET":
													s.handleHowEntityByRecordIDRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "GET")
												}

												return
											}

											elem = origElem
										case 'w': // Prefix: "why"
											origElem := elem
											if l := len("why"); len(elem) >= l && elem[0:l] == "why" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "GET":
													s.handleWhyEntityByRecordIDRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, "GET")
												}

												return
											}

											elem = origElem
										}

										elem = origElem
									}

									elem = origElem
								case 'r': // Prefix: "reevaluate"
									origElem := elem
									if l := len("reevaluate"); len(elem) >= l && elem[0:l] == "reevaluate" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleReevaluateRecordRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

									elem = origElem
								}

								elem = origElem
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'e': // Prefix: "entit"
				origElem := elem
				if l := len("entit"); len(elem) >= l && elem[0:l] == "entit" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ies"
					origElem := elem
					if l := len("ies"); len(elem) >= l && elem[0:l] == "ies" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleSearchEntitiesByGetRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "entityId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetEntityByEntityIdRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'h': // Prefix: "how"
								origElem := elem
								if l := len("how"); len(elem) >= l && elem[0:l] == "how" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleHowEntityByEntityIDRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "GET")
									}

									return
								}

								elem = origElem
							case 'w': // Prefix: "why"
								origElem := elem
								if l := len("why"); len(elem) >= l && elem[0:l] == "why" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleWhyEntityByEntityIDRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "GET")
									}

									return
								}

								elem = origElem
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				case 'y': // Prefix: "y-"
					origElem := elem
					if l := len("y-"); len(elem) >= l && elem[0:l] == "y-" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'n': // Prefix: "networks"
						origElem := elem
						if l := len("networks"); len(elem) >= l && elem[0:l] == "networks" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleFindEntityNetworkRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					case 'p': // Prefix: "paths"
						origElem := elem
						if l := len("paths"); len(elem) >= l && elem[0:l] == "paths" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleFindEntityPathRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'h': // Prefix: "heartbeat"
				origElem := elem
				if l := len("heartbeat"); len(elem) >= l && elem[0:l] == "heartbeat" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleHeartbeatRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'l': // Prefix: "license"
				origElem := elem
				if l := len("license"); len(elem) >= l && elem[0:l] == "license" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleLicenseRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'r': // Prefix: "reevaluate-entity"
				origElem := elem
				if l := len("reevaluate-entity"); len(elem) >= l && elem[0:l] == "reevaluate-entity" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleReevaluateEntityRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}

				elem = origElem
			case 's': // Prefix: "s"
				origElem := elem
				if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "e"
					origElem := elem
					if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "arch-entities"
						origElem := elem
						if l := len("arch-entities"); len(elem) >= l && elem[0:l] == "arch-entities" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleSearchEntitiesByPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

						elem = origElem
					case 'r': // Prefix: "rver-info"
						origElem := elem
						if l := len("rver-info"); len(elem) >= l && elem[0:l] == "rver-info" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetServerInfoRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					}

					elem = origElem
				case 'p': // Prefix: "pecifications/open-api"
					origElem := elem
					if l := len("pecifications/open-api"); len(elem) >= l && elem[0:l] == "pecifications/open-api" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleOpenAPISpecificationRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'v': // Prefix: "v"
				origElem := elem
				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "ersion"
					origElem := elem
					if l := len("ersion"); len(elem) >= l && elem[0:l] == "ersion" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleVersionRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				case 'i': // Prefix: "irtual-entities"
					origElem := elem
					if l := len("irtual-entities"); len(elem) >= l && elem[0:l] == "irtual-entities" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetVirtualEntityByRecordIdsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'w': // Prefix: "why/"
				origElem := elem
				if l := len("why/"); len(elem) >= l && elem[0:l] == "why/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "entities"
					origElem := elem
					if l := len("entities"); len(elem) >= l && elem[0:l] == "entities" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleWhyEntitiesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				case 'r': // Prefix: "records"
					origElem := elem
					if l := len("records"); len(elem) >= l && elem[0:l] == "records" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleWhyRecordsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"
			origElem := elem
			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch method {
				case "GET":
					r.name = "Root"
					r.summary = "Gets a root-level response from the server.  This returns the same as the `GET /heartbeat` endpoint for now, but may change in the future to provide additional information."
					r.operationID = "root"
					r.pathPattern = "/"
					r.args = args
					r.count = 0
					return r, true
				default:
					return
				}
			}
			switch elem[0] {
			case 'a': // Prefix: "attribute-types"
				origElem := elem
				if l := len("attribute-types"); len(elem) >= l && elem[0:l] == "attribute-types" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = "GetAttributeTypes"
						r.summary = "Get a list of configured attribute types."
						r.operationID = "getAttributeTypes"
						r.pathPattern = "/attribute-types"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "attributeCode"
					// Leaf parameter
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "GetAttributeType"
							r.summary = "Get the attribute type identified by the attribute code."
							r.operationID = "getAttributeType"
							r.pathPattern = "/attribute-types/{attributeCode}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'b': // Prefix: "bulk-data/"
				origElem := elem
				if l := len("bulk-data/"); len(elem) >= l && elem[0:l] == "bulk-data/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "analyze"
					origElem := elem
					if l := len("analyze"); len(elem) >= l && elem[0:l] == "analyze" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = "AnalyzeBulkRecords"
							r.summary = "Analyze a bulk data set of records. (Supports SSE / Supports Web Sockets)"
							r.operationID = "analyzeBulkRecords"
							r.pathPattern = "/bulk-data/analyze"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				case 'l': // Prefix: "load"
					origElem := elem
					if l := len("load"); len(elem) >= l && elem[0:l] == "load" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = "LoadBulkRecords"
							r.summary = "Load the records in the provided bulk data set. (Supports SSE / Supports Web Sockets)"
							r.operationID = "loadBulkRecords"
							r.pathPattern = "/bulk-data/load"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'c': // Prefix: "configs/"
				origElem := elem
				if l := len("configs/"); len(elem) >= l && elem[0:l] == "configs/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "active"
					origElem := elem
					if l := len("active"); len(elem) >= l && elem[0:l] == "active" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "GetActiveConfig"
							r.summary = "Gets the current active configuration as raw JSON, no interpretation."
							r.operationID = "getActiveConfig"
							r.pathPattern = "/configs/active"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				case 't': // Prefix: "template"
					origElem := elem
					if l := len("template"); len(elem) >= l && elem[0:l] == "template" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "GetTemplateConfig"
							r.summary = "Gets the base template configuration as raw JSON, no interpretation. This is the initial configuration for a new repository."
							r.operationID = "getTemplateConfig"
							r.pathPattern = "/configs/template"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'd': // Prefix: "data-sources"
				origElem := elem
				if l := len("data-sources"); len(elem) >= l && elem[0:l] == "data-sources" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = "GetDataSources"
						r.summary = "Get a list of configured data sources."
						r.operationID = "getDataSources"
						r.pathPattern = "/data-sources"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = "AddDataSources"
						r.summary = "Adds one or more new data sources to the current default configuration and reinitializes with the newly modified configuration."
						r.operationID = "addDataSources"
						r.pathPattern = "/data-sources"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "dataSourceCode"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = "GetDataSource"
							r.summary = "Gets the details on the specified data source."
							r.operationID = "getDataSource"
							r.pathPattern = "/data-sources/{dataSourceCode}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/records"
						origElem := elem
						if l := len("/records"); len(elem) >= l && elem[0:l] == "/records" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "POST":
								r.name = "AddRecordWithReturnedRecordId"
								r.summary = "Load a new record specified in a data source with either an auto-generated record ID or a `RECORD_ID` specified in the payload."
								r.operationID = "addRecordWithReturnedRecordId"
								r.pathPattern = "/data-sources/{dataSourceCode}/records"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "recordId"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = "DeleteRecord"
									r.summary = "Delete a record given its data source and record ID."
									r.operationID = "deleteRecord"
									r.pathPattern = "/data-sources/{dataSourceCode}/records/{recordId}"
									r.args = args
									r.count = 2
									return r, true
								case "GET":
									r.name = "GetRecord"
									r.summary = "Get an entity record by data source and record ID."
									r.operationID = "getRecord"
									r.pathPattern = "/data-sources/{dataSourceCode}/records/{recordId}"
									r.args = args
									r.count = 2
									return r, true
								case "PUT":
									r.name = "AddRecord"
									r.summary = "Load a new record or replace a record in a data source with a specific record ID."
									r.operationID = "addRecord"
									r.pathPattern = "/data-sources/{dataSourceCode}/records/{recordId}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"
								origElem := elem
								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'e': // Prefix: "entity"
									origElem := elem
									if l := len("entity"); len(elem) >= l && elem[0:l] == "entity" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch method {
										case "GET":
											r.name = "GetEntityByRecordId"
											r.summary = "Get a resolved entity by data source and record ID."
											r.operationID = "getEntityByRecordId"
											r.pathPattern = "/data-sources/{dataSourceCode}/records/{recordId}/entity"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/"
										origElem := elem
										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'h': // Prefix: "how"
											origElem := elem
											if l := len("how"); len(elem) >= l && elem[0:l] == "how" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "GET":
													r.name = "HowEntityByRecordID"
													r.summary = "Returns an analysis of how the entity for the record with the respective data source code and record ID resolved."
													r.operationID = "howEntityByRecordID"
													r.pathPattern = "/data-sources/{dataSourceCode}/records/{recordId}/entity/how"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										case 'w': // Prefix: "why"
											origElem := elem
											if l := len("why"); len(elem) >= l && elem[0:l] == "why" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "GET":
													r.name = "WhyEntityByRecordID"
													r.summary = "Returns an analysis of why the entity for the record with the respective data source code and record ID resolved."
													r.operationID = "whyEntityByRecordID"
													r.pathPattern = "/data-sources/{dataSourceCode}/records/{recordId}/entity/why"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

											elem = origElem
										}

										elem = origElem
									}

									elem = origElem
								case 'r': // Prefix: "reevaluate"
									origElem := elem
									if l := len("reevaluate"); len(elem) >= l && elem[0:l] == "reevaluate" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = "ReevaluateRecord"
											r.summary = "Reevaluate a record identified by a data source and record ID."
											r.operationID = "reevaluateRecord"
											r.pathPattern = "/data-sources/{dataSourceCode}/records/{recordId}/reevaluate"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}

								elem = origElem
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'e': // Prefix: "entit"
				origElem := elem
				if l := len("entit"); len(elem) >= l && elem[0:l] == "entit" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ies"
					origElem := elem
					if l := len("ies"); len(elem) >= l && elem[0:l] == "ies" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = "SearchEntitiesByGet"
							r.summary = "Search for entities that would resolve to or relate to the provided entity features."
							r.operationID = "searchEntitiesByGet"
							r.pathPattern = "/entities"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "entityId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = "GetEntityByEntityId"
								r.summary = "Get a resolved entity by entity ID."
								r.operationID = "getEntityByEntityId"
								r.pathPattern = "/entities/{entityId}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'h': // Prefix: "how"
								origElem := elem
								if l := len("how"); len(elem) >= l && elem[0:l] == "how" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = "HowEntityByEntityID"
										r.summary = "Returns an analysis of how the entity for the respective entity ID resolved."
										r.operationID = "howEntityByEntityID"
										r.pathPattern = "/entities/{entityId}/how"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							case 'w': // Prefix: "why"
								origElem := elem
								if l := len("why"); len(elem) >= l && elem[0:l] == "why" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = "WhyEntityByEntityID"
										r.summary = "Returns an analysis of why the entity for the respective entity ID resolved."
										r.operationID = "whyEntityByEntityID"
										r.pathPattern = "/entities/{entityId}/why"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				case 'y': // Prefix: "y-"
					origElem := elem
					if l := len("y-"); len(elem) >= l && elem[0:l] == "y-" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'n': // Prefix: "networks"
						origElem := elem
						if l := len("networks"); len(elem) >= l && elem[0:l] == "networks" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = "FindEntityNetwork"
								r.summary = "Finds the entity network around one or more entities."
								r.operationID = "findEntityNetwork"
								r.pathPattern = "/entity-networks"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					case 'p': // Prefix: "paths"
						origElem := elem
						if l := len("paths"); len(elem) >= l && elem[0:l] == "paths" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = "FindEntityPath"
								r.summary = "Finds a path between two entities identified by entity ID or by data sources and record IDs of constituent records."
								r.operationID = "findEntityPath"
								r.pathPattern = "/entity-paths"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'h': // Prefix: "heartbeat"
				origElem := elem
				if l := len("heartbeat"); len(elem) >= l && elem[0:l] == "heartbeat" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "Heartbeat"
						r.summary = "Gets a heartbeat from the server to make sure it is up and running.  The response will include the current timestamp."
						r.operationID = "heartbeat"
						r.pathPattern = "/heartbeat"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'l': // Prefix: "license"
				origElem := elem
				if l := len("license"); len(elem) >= l && elem[0:l] == "license" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "License"
						r.summary = "Get the license information."
						r.operationID = "license"
						r.pathPattern = "/license"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'r': // Prefix: "reevaluate-entity"
				origElem := elem
				if l := len("reevaluate-entity"); len(elem) >= l && elem[0:l] == "reevaluate-entity" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = "ReevaluateEntity"
						r.summary = "Reevaluate an entity identified by its entity ID."
						r.operationID = "reevaluateEntity"
						r.pathPattern = "/reevaluate-entity"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 's': // Prefix: "s"
				origElem := elem
				if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "e"
					origElem := elem
					if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "arch-entities"
						origElem := elem
						if l := len("arch-entities"); len(elem) >= l && elem[0:l] == "arch-entities" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = "SearchEntitiesByPost"
								r.summary = "Search for entities that would match or relate to the provided entity features.  This is similar to `GET /entities` except it requires the caller to specify the search criteria as JSON in the request body."
								r.operationID = "searchEntitiesByPost"
								r.pathPattern = "/search-entities"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					case 'r': // Prefix: "rver-info"
						origElem := elem
						if l := len("rver-info"); len(elem) >= l && elem[0:l] == "rver-info" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = "GetServerInfo"
								r.summary = "Get info regarding the server's state and supported features."
								r.operationID = "getServerInfo"
								r.pathPattern = "/server-info"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}

					elem = origElem
				case 'p': // Prefix: "pecifications/open-api"
					origElem := elem
					if l := len("pecifications/open-api"); len(elem) >= l && elem[0:l] == "pecifications/open-api" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "OpenAPISpecification"
							r.summary = "Gets this Open API specification to describe the API."
							r.operationID = "openAPISpecification"
							r.pathPattern = "/specifications/open-api"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'v': // Prefix: "v"
				origElem := elem
				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "ersion"
					origElem := elem
					if l := len("ersion"); len(elem) >= l && elem[0:l] == "ersion" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "Version"
							r.summary = "Get the full version information."
							r.operationID = "version"
							r.pathPattern = "/version"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				case 'i': // Prefix: "irtual-entities"
					origElem := elem
					if l := len("irtual-entities"); len(elem) >= l && elem[0:l] == "irtual-entities" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "GetVirtualEntityByRecordIds"
							r.summary = "Builds a virtual entity by simulating the resolution of the records identified by the specified record ID parameters."
							r.operationID = "getVirtualEntityByRecordIds"
							r.pathPattern = "/virtual-entities"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'w': // Prefix: "why/"
				origElem := elem
				if l := len("why/"); len(elem) >= l && elem[0:l] == "why/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "entities"
					origElem := elem
					if l := len("entities"); len(elem) >= l && elem[0:l] == "entities" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "WhyEntities"
							r.summary = "Returns an analysis of why the two entities related, did not relate, or did not resolve."
							r.operationID = "whyEntities"
							r.pathPattern = "/why/entities"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				case 'r': // Prefix: "records"
					origElem := elem
					if l := len("records"); len(elem) >= l && elem[0:l] == "records" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "WhyRecords"
							r.summary = "Returns an analysis of why the records identified by the data source and record ID's in the query parameters resolved or did not resolve."
							r.operationID = "whyRecords"
							r.pathPattern = "/why/records"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	return r, false
}
