# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-darwin.yaml

on: [push]

env:
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

jobs:
  build:
    runs-on: macos-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
    strategy:
      matrix:
        go: ["1.20"]
    name: Go ${{ matrix.go }} - darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Download SenzingApi
        run: curl --output /tmp/senzingapi.dmg https://public-read-access.s3.amazonaws.com/staging/senzingapi.dmg
      - name: Attach .dmg
        run: hdiutil attach /tmp/senzingapi.dmg
      - name: Copy SenzingApi files
        run: sudo mkdir -p /opt/senzing/    && sudo cp -R /Volumes/SenzingAPI/senzing/g2 /opt/senzing
      - name: Copy /etc files
        run: sudo cp testdata/senzing-license/g2.lic /opt/senzing/etc
      - name: Copy test database fies
        run: mkdir /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db
      - name: Run go test
        run: go test -exec /Users/runner/work/go-rest-api-service/go-rest-api-service/bin/macos_exec_dyld.sh -v -p 1 ./...
